# Site settings
title: WangShuShu Blog
motto: My surname really is Wang，I promise
email: NeighborWangShuShu@Gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://github.com/NeighborWangShushu/neighborwangshushu.github.com" # the base hostname & protocol for your site
twitter_username: neighborwangshu
facebook_username: neighborwangshushu
github_username:  NeighborWangShuShu

# Build settings
markdown: kramdown
highlighter: Pygments

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: true
